[package]
name = "Coral"
version = "0.1.0"
edition = "2024"

[dependencies]
terminal_size = "0.4.2"
libc = "0.2.173"
ctrlc = "3.4.7"
colorgrad = "0.7.2"
colored = "3.0.0"
rand = "0.9.2"
owo-colors = "4.2.2"
